version: "2"

services:
  nginx:
    container_name: nginx
    image: nginx:1.17.8-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ubuntu/nginx/conf.d:/etc/nginx/conf.d/:rw
      - /home/ubuntu/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - server
    restart: always
  mysql:
    container_name: mysql
    image: tobi312/rpi-mysql:latest
    volumes:
      - /path:/etc/mysql/my.cnf
      - /path:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    networks:
      - server
      
networks:
  server:
    driver: bridge
