version: "2"

services:
  nginx:
    container_name: nginx
    image: nginx:1.17.8-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /path/nginx/conf.d:/etc/nginx/conf.d/:rw
      - /path/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default
    restart: always
  mysql:
    container_name: mysql
    image: mysql:5.6
    volumes:
      - /path/mysql/my.cnf:/etc/mysql/my.cnf
      - /path/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    networks:
      - default
      
networks:
  default:
    external:
      name: server
